import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import styled from "styled-components";
import connectToMongo from "../util/mongo";

export default function Home() {
  const depts = await fetch("api/getDepts");
  console.log(depts);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

// export async function getStaticProps() {
//   const departments = await fetch("http://localhost:3000/api/getDepts");
//   return {
//     props: {
//       departments: departments.map((d) => ({
//         id: d._id.toString(),
//         title: d.name,
//         courses: d.courses,
//       })),
//     },
//   };
// }
