import Head from "next/head";
// import styles from "../styles/Home.module.css";
import styled from "styled-components";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
export async function getStaticProps(context) {
    const response=await fetch('http://localhost:3000/api/getDepts');
    const data=await response.json(); 
  return {
    props: {data}, // will be passed to the page component as props
  }
}



